plugins {
    id 'dev.architectury.loom'
}

loom {
    silentMojangMappingsLicense()
}

architectury {
    common(rootProject.enabled_platforms.split(","))
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    sourceSets.main.resources.sourceDirectories.each { dir ->
        commonResources dir
    }
}

dependencies {
    // Minecraft
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_mappings}@zip")
    }
    
    // Architectury API
    modImplementation "dev.architectury:architectury:$architectury_api_version"
    // EMI
    modCompileOnly "dev.emi:emi-xplat-mojmap:${emi_version}:api"
    // GeckoLib
    modImplementation "software.bernie.geckolib:geckolib-common-${minecraft_version}:$geckolib_version"
    // Jade
    modCompileOnly "curse.maven:jade-324717:4780011"
    // JEI
    modCompileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}") { transitive = false }
    // owo-lib
    modCompileOnly "io.wispforest:owo-lib:$owo_version"
    annotationProcessor "io.wispforest:owo-lib:$owo_version"
    // REI
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api:$rei_version"
}
